### ISSUE TITLE
Error: Unrecognized import path "hive"

### ISSUE THREAD

**Issue by m4rouf** [njpatel/hivekit#12]
I'm getting this error when I try to install the packages:

./main.go:30: undefined: hap.Transport
./main.go:85: undefined: hap.Config
./main.go:90: undefined: hap.NewIPTransport

Please help!

**Comment by njpatel** [comment]
HiveKit isn't "go get-able" so you have to follow the instructions here to build it locally: https://github.com/njpatel/hivekit#getting-started
